### ISSUE TITLE
IOS Blank Screen

### ISSUE THREAD

**Issue by iambudi** [FranPitri/flutter_redux_boilerplate#1]
Thanks for sharing the code.
I tried to run on Ios simulator but it's blank (white screen). No error at all.

**Comment by pitriq** [comment]
Hi there! I should point out that this project is under active development (it is not finished yet!), so the master branch (project's only branch) is kind of unstable at the moment. I will add that to the readme, along with some milestones.

What's currently happening is that the root ('/') path is redirecting to a blank screen (It should have a Spinner on it, that's another issue haha). I haven't written the Middleware that changes screens on certain actions (login, logout, store rehydrated) yet, so currently it will be stuck forever in that screen.

**Comment by pitriq** [comment]
It should be fixed now! Haven't actually taken the middleware approach, I opted for adding a new field to the State to indicate whether it has been rehydrated or not. 

Now LoadingScreen waits until the state has been fully rehydrated, and then navigates to LoginScreen or MainScreen, depending on the auth state.
