### ISSUE TITLE
Redux_persist usage

### ISSUE THREAD

**Issue by Cretezy** [FranPitri/flutter_redux_boilerplate#2]
Hey! Creator of redux_persist here.

Just wanted to note that the PersistorGate should go *over* the whole app, and if you want a loading screen, use the `loading` field on the gate, to be shown while loading.

Let me know if you have any questions or if you have an suggestions to make the document clearer to future pitfalls by others people :)

**Comment by pitriq** [comment]
Hey! Amazing package; and thanks for the suggestion! I will update the project ASAP.

Maybe you could point this out in redux_persist_flutter's readme example ([example project](https://github.com/Cretezy/redux_persist/blob/master/packages/redux_persist_flutter/example/redux_persist_flutter_example.dart) is great though, I hadn't checked that out when I implemented PresistorGate)

**Comment by pitriq** [comment]
Please check https://github.com/FranPitri/flutter_redux_boilerplate/commit/7dea764c2afc1d036a793b07cd34645eb38b1ce4 and tell me what do you think!

**Comment by Cretezy** [comment]
Looks better! :)

**Comment by ghost** [comment]
Thanks for making this. Really useful for me !!!
