### ISSUE TITLE
xcode ld: library not found for -lpath_provider

### ISSUE THREAD

**Issue by hjlxy** [FranPitri/flutter_redux_boilerplate#4]
<img width="734" alt="wx20180411-094402 2x" src="https://user-images.githubusercontent.com/17348119/38592154-0134924e-3d6d-11e8-84bc-2c170dd46e04.png">

**Comment by hjlxy** [comment]
Here's my version of Flutter:

Flutter 0.2.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision b397406561 (8 days ago) • 2018-04-02 13:53:20 -0700
Engine • revision c903c217a1
Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357

**Comment by pitriq** [comment]
Hello! That seems to be an Xcode configuration related issue. I don't own a Mac so I couldn't really replicate it. It'd be great to see if anyone else encounters this problem. 

Anyway, what branch are you running? Have you tried `develop` latest changes? I have updated most of this repo's dependencies there. I haven't yet merged it to master since I'm waiting for some feedback.

**Comment by hjlxy** [comment]
Thanks for this repo, it's really useful!
Flutter 0.2.3 • channel beta
Test success on Android.But in Flutter 0.2.10(0.2.9) channel dev, the test failed.
on Android:
I/FlutterActivityDelegate(26347): onResume setting current activity to this
E/flutter (26347): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (26347): type 'List<dynamic>' is not a subtype of type 'List<(Store<AppState>, dynamic, (dynamic) => void) => void>' where
E/flutter (26347):   List is from dart:core
E/flutter (26347):   List is from dart:core
E/flutter (26347): 
E/flutter (26347): #0      createStore (package:flutter_redux_boilerplate/store/store.dart:11:21)
E/flutter (26347): #1      new ReduxApp (file:///Volumes/data/dev/mobile/flutter_redux_boilerplate/lib/main.dart:16:19)
E/flutter (26347): #2      main (file:///Volumes/data/dev/mobile/flutter_redux_boilerplate/lib/main.dart:13:27)
E/flutter (26347): #3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
E/flutter (26347): #4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

on IOS:
Xcode's output:
↳
    === BUILD TARGET shared_preferences OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/hj/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-0.3.1/ios/Classes/PathProviderPlugin.m:5:
    /Users/hj/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-0.3.1/ios/Classes/PathProviderPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/hj/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.1/ios/Classes/SharedPreferencesPlugin.m:5:
    /Users/hj/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.1/ios/Classes/SharedPreferencesPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by hjlxy** [comment]
<img width="1046" alt="wx20180412-103849 2x" src="https://user-images.githubusercontent.com/17348119/38653519-c1e9ba7a-3e3d-11e8-805e-fa0b8d472d67.png">

**Comment by pitriq** [comment]
That error appears in the latest flutter builds (those have dart2 enabled by default). This was fixed in `develop`'s branch last commit. Please, pull that branch and try to run the project, and tell me how it goes!

**Comment by hjlxy** [comment]
my version of Flutter:
Flutter 0.2.10 • channel dev • https://github.com/flutter/flutter.git
Framework • revision d6d874474b (6 days ago) • 2018-04-06 13:23:16 -0700
Engine • revision d2b69fec75
Tools • Dart 2.0.0-dev.46.0.flutter-09e1766e6c

The Android and IOS tests have been successful！
UI has a little problem in IOS, and I can modify it.

Thank you very much for your help!
