### ISSUE TITLE
Why login_form uses statefull widget ?

### ISSUE THREAD

**Issue by rubensdemelo** [FranPitri/flutter_redux_boilerplate#6]
Im starting with flutter + redux and would like to know why did you use a statefull widget in login_form?

**Comment by pitriq** [comment]
Hello!

I wrote it as a stateful wigdet so as to keep a form key in state. That way you can have the  authentication data validated before actually calling the login action.

**Comment by rubensdemelo** [comment]
Got it. Thank you!
