### ISSUE TITLE
authReducer return values

### ISSUE THREAD

**Issue by alexandropavlov** [FranPitri/flutter_redux_boilerplate#9]
Hey man! Сool project. 
I'm new in Flutter, and trying to figure out how to implement redux in my project.
So it was worth for me to see this example.

I noticed, that in **reducers/auth_reducer.dart** in reducers you return
```
new AuthState().copyWith(...
```
but, shouldn't it be
```
auth.copyWith(...
```
?

**Comment by pitriq** [comment]
Hey there! You're right man, I totally overlooked that one since it wasn't actually breaking anything in this particular case 😁.

Gonna make sure to update it, thanks!
